### ISSUE TITLE
CSAR export without normative types

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-gmt#1]
The TOSCA standard already defines and brings initial types that orchestartors should _understand_. Therefore those definition files [1] and references[2] in the blueprints can be removed from the CSAR exports.

Option: Winery cloud have a checkbox for including/excluding normative types.

**[1] Files**

![2020-03-09 14_42_01-WinMerge -  ToyExample_ - ToyExampleSemiFixed_](https://user-images.githubusercontent.com/2518386/76218557-b55f2180-6214-11ea-943f-23cd6e8714d6.png)

**[2] references**

![2020-03-09 14_38_17-WinMerge -  radonblueprints__ToyExample tosca x 2](https://user-images.githubusercontent.com/2518386/76218576-bdb75c80-6214-11ea-8084-c3a77b339b71.png)

**Comment by miwurster** [comment]
Fixed in latest `master`.
