### ISSUE TITLE
Number values in TOSCA yaml should be "string".

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-gmt#2]
The TOSCA standard treats all number values in the yaml files as strings, e.g.:

all 
`count: 5`

should be 

`count: "5"`

see example in the figure:

![2020-03-09 14_48_26-WinMerge -  radonblueprints__ToyExample tosca x 2](https://user-images.githubusercontent.com/2518386/76218996-682f7f80-6215-11ea-8611-05c68abf8e2b.png)

**Comment by miwurster** [comment]
Fixed in latest `master`.
