### ISSUE TITLE
Duplicate namespace for derived nodes types in CSAR export

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-gmt#21]
Example: 

When exporting the CSAR for `radon.nodes.Workstation`, the file `radonnodes__Workstation.tosca` includes the namespace definition `radon.nodes.radon.nodes.Workstation`, i.e., a duplicate namespace `radon.nodes`.

**Comment by v-yussupov** [comment]
Just checked it: if the targetNamespace value is specified in metadata, the exported namespace is corrupted, I will fix it, thanks for reporting it!

**Comment by miwurster** [comment]
Fixed by https://github.com/OpenTOSCA/winery/pull/192
