### ISSUE TITLE
Node type interface implementation  

### ISSUE THREAD

**Issue by chinmaya-dehury** [radon-h2020/radon-gmt#23]
Hi, 
I was defining the **Interfaces** of a node type. Provided the inputs to the standard lifecycle operations, such as _create_, _configure_, _start_, etc.. But kind of stuck with the implementation (Ansible) files. 
Where to provide the node type implementation files, such as _create.yml_, _delete.yml_, _configure.yml_, _start.yml_ etc. in the RADON-GMT interface? 
Is the GMT expecting those Ansible implementations through Artifacts?

-Regards

**Comment by miwurster** [comment]
Hey @chinmaya-dehury, sorry for the late response. Yes, GMT expects these to be uploaded as "artifacts". Go to the "Artifacts" tab in the node type UI and upload the files. Afterward, you can go back to "Interface Definitions" and assign these artifacts (either as primary artifact or dependency). Hope this helps.

**Comment by miwurster** [comment]
Assuming the issue is resolved. Re-open it if you still have questions concerning this issue.
