### ISSUE TITLE
Unclear README.me instructions

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/radon-gmt#24]
I am trying to install Winery.

Presentation problems with the README:
- "There was no security of Eclipse Winey."
-  is rendered at ->  is available at
- It does not say that you have to clone it first and cd into the folder
- "You can also use the pre-built image and bin it to a local repository:" this sentence is not clear. Why should one want to do this.
- Section "Next steps": this part is not getting started. Put it in the Issues?
- Now that it's running what shoudl I do? Plese include a minimal
getting started.
----------------------------
Some errors during installation:
[INFO]
[INFO] --- frontend-maven-plugin:1.6:npm (build tosca-management) @
org.eclipse.winery.frontends ---
[INFO] Running 'npm run build-tosca-management-prod' in
/tmp/winery/org.eclipse.winery.frontends
[INFO]
[INFO] > winery-frontends@2.0.0-SNAPSHOT build-tosca-management-prod
/tmp/winery/org.eclipse.winery.frontends
[INFO] > ng build tosca-management --prod
[INFO]
[ERROR] Browserslist: caniuse-lite is outdated. Please run next
command `npm update`
----------------------------
[INFO] Linting "tosca-management"...
[ERROR] Warning: member-ordering - Got empty options
----------------------------
[INFO] Linting "topologymodeler"...
[ERROR] Warning: member-ordering - Got empty options
----------------------------
[INFO]
[ERROR] Browserslist: caniuse-lite is outdated. Please run next
command `npm update`
----------------------------

**Comment by miwurster** [comment]
Don't worry, these entries don't show build errors. The build only determines some `npm build` stuff as error logs.

**Comment by miwurster** [comment]
At the moment we cannot update the README at https://github.com/radon-h2020/radon-gmt as the `project/radon` branch is currently processed by the Eclipse team to merge it into `master`. In the meantime, please refer to the official README at https://github.com/eclipse/winery.

**Comment by miwurster** [comment]
RADON-related changes have been merged into the Eclipse Winery's `master` branch. Updated the README and redirect respectively to the docs on read-the-docs.
