### ISSUE TITLE
What namespace to indicate?

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/radon-gmt#25]
I am following the GMT getting started at:
https://eclipse-winery.readthedocs.io/en/latest/user/yml/index.html#modeling-an-application

What should one indicate in the namespace? If I follow what shown in the video I get nowhere as the Editor starts with an error and then there are no graphical elements available to draw the TOSCA model

![image](https://user-images.githubusercontent.com/4592912/82320687-95459e80-99cb-11ea-8cdb-0ab862c42726.png)

**Comment by miwurster** [comment]
What kind of error did the editor show? The image you posted don't show errors. These are just "info" messages.

Have you started Winery based on the instructions available here?
https://eclipse-winery.readthedocs.io/en/latest/user/getting-started.html#launching-with-docker

If you have no types for modeling you may missed to set the `WINERY_REPOSITORY_URL` variable at `docker run ...`.

**Comment by gcasale** [comment]
Before I was using the README.md instructions for the initial bootstrap.

I have now cloned restarted docker, went to a new folder without cloning
gmt into it, and simply typed:

docker run -it -p 8080:8080 \
  -e PUBLIC_HOSTNAME=localhost \
  -e WINERY_FEATURE_RADON=true \
  -e WINERY_REPOSITORY_PROVIDER=yaml \
  -e WINERY_REPOSITORY_URL=https://github.com/radon-h2020/radon-particles \
  opentosca/winery


At the end of the process this is what I get:



[image: image.png]

With console output:
12:10:53.936 [http-nio-8080-exec-9] INFO
 o.g.jersey.logging.LoggingFeature:132 log - 9 * Server has received a
request on thread http-nio-8080-exec-9
9 > GET http://146.169.50.82:8080/winery/admin/namespaces/
9 > accept: application/json
9 > accept-encoding: gzip, deflate
9 > accept-language: en-US,en;q=0.9,de;q=0.8,es;q=0.7,it;q=0.6
9 > connection: keep-alive
9 > host: 146.169.50.82:8080
9 > referer: http://146.169.50.82:8080/
9 > user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

12:10:53.937 [http-nio-8080-exec-9] INFO
 o.g.jersey.logging.LoggingFeature:132 log - 9 * Server responded with a
response on thread http-nio-8080-exec-9
9 < 200
9 < Content-Type: application/json
[ ]

12:10:53.942 [http-nio-8080-exec-5] ERROR
o.e.w.r.backend.AbstractRepository:121 getDefinitions - Could not read
content from file RepositoryFileReference{parent=class
org.eclipse.winery.common.ids.definitions.ServiceTemplateId /
{radon.blueprints.testing}ABMasterOnly, subDirectory=Optional.empty,
fileName='ServiceTemplate.tosca'}
javax.xml.bind.UnmarshalException: null
        at
javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)

**Comment by miwurster** [comment]
You were using a wrong Docker image most probably due to an outdated getting started guide. Please check the command again. However, make sure you are using the `opentosca/radon-gmt` Docker image.

**Comment by miwurster** [comment]
Further, I added a [hint](https://eclipse-winery.readthedocs.io/en/latest/user/yml/index.html#modeling-an-application) on what to put into the "namespace" field.
Essentially it's there to group your service templates, e.g., into `com.example.blueprints` and/or `radon.blueprints` etc.

**Comment by gcasale** [comment]
Works well now, thanks a lot.
