### ISSUE TITLE
Inserting `unbounded` word instead of `UNBOUNDED` into the tosca file.

### ISSUE THREAD

**Issue by chinmaya-dehury** [radon-h2020/radon-gmt#26]
In `Node Types` -> `Capabilities Definitions` -> `Add` button -> now clicked on `infinite` symbol to set the `Uppe Bound` as UNBOUNDED.
This adds the word  “unbounded” instead of “UNBOUNDED” in the corresponding tosca file. 
For orchestrator “unbounded” is a foreign word and throws error saying it should be either a numeric value or “UNBOUNDED”.

-Thanks

**Comment by miwurster** [comment]
Fixed by eclipse/winery#492.
