### ISSUE TITLE
[R-T4.3-11] Referencing files as URLs

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/radon-gmt#27]
| **ID** | **R-T4.3-11** |
|---|---|
| Section | WP4: Modeling Environment |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to change my application's business logic but don't want to update my RADON Model after any change. |
| Requirement | There must be the possibility to reference business logic as a URL to make it possible to change the business logic of the application without changing the RADON Model. |
| Extended Description | The GMT at M12 expected all files to be physically present in a RADON Model. This means that any business logic (e.g., the function code for FaaS) needs to be uploaded in a respective packaging format (e.g., ZIP for Python- or NodeJS-based functions or JAR for Java-based functions) prior to deploying the applications. As developers may utilize multiple functions, and these functions may change very often, the manual task to push the new business logic to the GMT becomes tedious and is not very DevOps-like where you want to automate things. Therefore, there must be the possibility to reference any business logic as a URL, either staged in an accessible storage location or in a binary and build artifact management tools, such as Sonatype Nexus or JFrog Artifactory. This will make it possible to change the business logic of the application but does not require to update the RADON Model. |
| Affected Tools | GRAPHMODEL_TOOL |
| Means of Verification | Manual testing based on case studies. |
| Dependency | N/A |

**Comment by miwurster** [comment]
@gcasale please approve new requirement.

**Comment by gcasale** [comment]
Approved

**Comment by v-yussupov** [comment]
Solved in the context of https://github.com/eclipse/winery/pull/465 and https://github.com/eclipse/winery/pull/523
