### ISSUE TITLE
[R-T4.3-12] Manage company-specific RADON Models and TOSCA entity type

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/radon-gmt#28]
| **ID** | **R-T4.3-12** |
|---|---|
| Section | WP4: Modeling Environment |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to store and version my company-specific RADON Model separately from RADON Particles. |
| Requirement | GMT must be initialized and start based on the RADON Particles, but company-specific RADON Models as well as custom TOSCA entity types must be stored differently. |
| Extended Description | In RADON, we publish and maintain RADON Models as well as reusable TOSCA entity types to a public GitHub repository called the RADON Particles. This repository, on the one hand, serves as an example of a public RADON Template Library (cf. D5.4 Technology Library and D4.4 RADON Models II) and, on the other hand, provides a modeling baseline for RADON users that want to use the GMT to compose application blueprints. So, it is important to use the current RADON Particles master branch when starting the GMT. However, at the same time, companies that model applications want to store their models separately from the public one, e.g. to push and manage them in their internal and private Git repository, such as GitLab. Therefore, there must be the possibility to initialize and start the GMT based on the RADON Particles, but company-specific RADON Models as well as custom TOSCA entity types must be stored differently. The GMT needs a way to separate the modeling entities into multiple repositories. |
| Affected Tools | GRAPHMODEL_TOOL |
| Means of Verification | Manual testing based on case studies. |
| Dependency | N/A |

**Comment by miwurster** [comment]
@gcasale please approve new requirement.

**Comment by gcasale** [comment]
This is a should have in my view. This is a business scenario but the system can work also with particle alone so I don't regard it as a must have.

**Comment by gcasale** [comment]
Approved

**Comment by v-yussupov** [comment]
Fixed with the multirepository feature addressed by eclipse#465, eclipse#523, and https://github.com/eclipse/winery/pull/567
