### ISSUE TITLE
[R-T4.3-13] Save exported CSAR to the filesystem

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/radon-gmt#29]
| **ID** | **R-T4.3-13** |
|---|---|
| Section | WP4: Modeling Environment |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to generate and save a CSAR to my Eclipse Che workspace to utilize other RADON tools, e.g., to analyze my CSAR prior to deployment. |
| Requirement | Save generated CSARs to Eclipse Che’s workspace to enable further processing by other RADON tools. |
| Extended Description | This requirement arose when we first integrated RADON tools with the RADON IDE based on Eclipse Che. The GMT is the central tool to generate a TOSCA CSAR, which is required by the RADON Orchestrator to deploy the application therein. Also, the integration point with other tools is also an executable CSAR, e.g., the Defect Prediction can analyze the content prior to deployment. Therefore, the GMT must be able to save the generated CSAR to Eclipse Che’s workspace. This enables other tools to further process the CSAR prior to deploying it using the RADON Orchestrator. |
| Affected Tools | GRAPHMODEL_TOOL |
| Means of Verification | Manual testing based on case studies. |
| Dependency | N/A |

**Comment by miwurster** [comment]
@gcasale please approve new requirement.

**Comment by gcasale** [comment]
Approved. Typo: to enables  -> to enable

**Comment by v-yussupov** [comment]
Solved by https://github.com/eclipse/winery/pull/465
