### ISSUE TITLE
Error exporting csar when running Winery on "multi-repository" mode.

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-gmt#33]
When running Eclipse Winery in the “multi-repository” setup, (fetching the radon-particles from git but storing my service template on my local workspace) I can't export the csar. 

HTTP Status 500 – Internal Server Error is the feedback, whether the service template resides in "workspace" directory or in the radon-particles service templates.

[error_log_export_csar.txt](https://github.com/radon-h2020/radon-gmt/files/4771538/error_log_export_csar.txt)

**Comment by miwurster** [comment]
Fixed by latest version.
