### ISSUE TITLE
Launching docker container on cloud platform

### ISSUE THREAD

**Issue by Philips-SSP** [radon-h2020/radon-gmt#37]
Hi everyone,

I am just starting out with the GMT, how would I define and create a docker container running on a cloud platform?

My first try was to use a radon.nodes.docker.DockerApplication (or the tosca.nodes.container perhaps?) and a radon.nodes.google.GoogleCloudPlatform node, then connect the DockerApplication.requirement-host:HostedOn to GoogleCloudPlatform.capabilities-host, but it gives me the message: "The selected requirement and capability are not compatible".

Moreover, once this relationship is defined, how do I load my actual application into the DockerApplication node? Upload the Dockerfile and all code somewhere in the workspace, then through 'artifacts' in Winery?

**Comment by miwurster** [comment]
Hello,

atm you could run a Docker container on your local dev machine or a virtual machine hosted on OpenStack or AWS (EC2). However, the Docker container requires the `DockerRuntime` to be present and hosted on a valid compute node, which is in this case either a `Workstation`, `OpenStack`, or `EC2` node.

On top of the `DockerRuntime` you would then add a `DockerApplication` node (connected with a `hosted on` relation). However, the current `DockerApplication` node is *abstract* which means it cannot be deployed and used directly in a service template. Therefore, a concrete subtype needs to be created for your custom application. Similarly, we did this for the [`DeploymentTestAgent`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.testing/DeploymentTestAgent) node inside the particles. Essentially this is a subtype of `DockerApplication` containing its own Ansible implementation with the [instructions on how to run the container](https://github.com/radon-h2020/radon-particles/blob/master/nodetypes/radon.nodes.testing/DeploymentTestAgent/files/create/create.yml).

A complete example can be found [here](https://github.com/radon-h2020/radon-particles/blob/master/servicetemplates/radon.blueprints.testing/DeploymentTestAgent/ServiceTemplate.tosca).

Let us know if you need further assistance.

Best,
Michael

**Comment by miwurster** [comment]
Closed due to inactivity.
