### ISSUE TITLE
Corrupted Artifact attachment using artifact URL

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-gmt#39]
When I attach my artifact which is stored on FunctionHub using the URL, the downloaded file which resides in the .csar deployable file seems to be corrupted. It is smaller in size, and can not get unzipped. Thus, the deployment of the lambda is prevented.

Trying to open the corrupted file manually give me the following message
<img width="1200" alt="Screenshot 2020-09-15 at 10 45 48" src="https://user-images.githubusercontent.com/23174477/93190778-0e6bbd00-f744-11ea-8cfc-4be134bf517b.png">

**Comment by miwurster** [comment]
Fixed by f3bc31ca85ca7831aa4a42f63fff5ba7920fc3a6
