### ISSUE TITLE
GMT - [feature request] Node Type descriptions

### ISSUE THREAD

**Issue by kk-0129** [radon-h2020/radon-gmt#44]
Node types in the GMT are described by name only, but the name alone is not always sufficient to explain what the node is and how/when it should best be used.
e.g.
- what is a "radon.nodes.datapipeline.MidwayPB" node type? (it is not described in D4.3 'RADON Models I Companion', nor "radon-ide.readthedocs.io", and the README.md in the code repository simply says that "This acts as the root node for all midway pipeline blocks." -  from which I can deduce that the 'B' probably stands for 'block', but not much else),
- what is the difference between "radon.nodes.aws.AwsS3Bucket" and "radon.nodes.legacy.AwsS3Bucket"?
- does "radon.nodes.datapipeline.process.AWSLambda" represent an invokable function? If so, is it different from "radon.nodes.legacy.AwsLambdaFunction"?
.. and so on ....
More informative descriptions of node types, easily accessible through the GUI (e.g.. by clicking an info '(i)' symbol on the node type), would be very helpful.

**Comment by miwurster** [comment]
Everything inside `radon.nodes.datapipeline.*` is used for data pipeline modeling. You'll find more information about the usage in the respective deliverables about "Data Pipeline Orchestration". 

Legacy node types are all marked as `deprecated` and only in the particles for backward compatibility purposes:
![image](https://user-images.githubusercontent.com/2610997/94647678-44d33b80-02f1-11eb-9e9f-0eafc845d1fc.png)


The type `radon.nodes.datapipeline.process.AWSLambda` can only be used together with other data pipeline nodes. You will find more information about this in the respective deliverable. Maybe @chinmaya-dehury can give you a quick intro here...

**Comment by chinmaya-dehury** [comment]
That's right @miwurster . The `radon.nodes.datapipeline.process.AWSLambda` node type can only be connected to other data pipeline node types. 

@kk-0129 , Basically, data pipeline nodes are developed keeping the flow of data across multiple cloud systems in mind. All nodes falling under  "`radon.nodes.datapipeline.*`" can be easily connected to each other without much worrying about the data. For instance, relatively it is very easy to connect pipeline-based `AWSLambda` function to pipeline-based `OpenFaaS` function. Similarly, data can be sent from `S3Bucket` (using "`radon.nodes.datapipeline.source.ConsS3Bucket`" node type) to Google cloud storage (using "`radon.nodes.datapipeline.destination.PubGCS`" node type ) without worrying about the data handling mechanisms. 

The detailed information can be found in our [current](http://radon-h2020.eu/wp-content/uploads/2020/01/D5.5-Data-Pipeline-Orchestration-I.pdf) and upcoming deliverables. We will also update our [datapipeline-plugin.readthedocs.io](https://datapipeline-plugin.readthedocs.io/en/latest/) with these information very soon.
