### ISSUE TITLE
GMT - Node type definition: properly handle empty string as default values in properties

### ISSUE THREAD

**Issue by kmlTE** [radon-h2020/radon-gmt#50]
# Current behavior
When two consecutive properties are added with empty string ("") as a default value, only one property gets default empty string value in TOSCA. For example, adding "docker_user" and "docker_pass" properties with default value (""):
![Screenshot from 2021-03-25 15-29-16](https://user-images.githubusercontent.com/2138519/112489937-34bb8680-8d7f-11eb-8cbf-5eb86eb5e38b.png)

Produces this TOSCA:
![Screenshot from 2021-03-25 15-33-41](https://user-images.githubusercontent.com/2138519/112490256-8106c680-8d7f-11eb-8e3f-41fc8dc19ed4.png)

# Desired behavior
Both properties should have default empty string values

**Comment by miwurster** [comment]
This is currently not supported, unfortunately. The Winery parser/serializer strips off empty values atm.

I'll track it in our main repo for higher visibility.

**Comment by miwurster** [comment]
Hi @kmlTE, we fixed this in the upstream and it should be available within the latest Docker image (https://github.com/eclipse/winery/pull/573). 

To enter an empty string value, users have to enter `""` in the properties add/edit popup. This should result in the correct yaml syntax. 

If you could verify at your end, I would then close the issue.

**Comment by v-yussupov** [comment]
Hi @kmlTE, please let us know if the issue is resolved for you, then we can close the issue. Thanks!

**Comment by kmlTE** [comment]
@v-yussupov @miwurster this issue is now resolved, thank you!
