### ISSUE TITLE
[R-T4.3-4] Definition of constraints

### ISSUE THREAD

**Issue by v-yussupov** [radon-h2020/radon-gmt#7]
| **ID**                        |  **R-T4.3-4**                              |
|-----------------------|----------------------------------|
| Section                       |  WP4: Modeling Environment     |
| Type                           |  FUNCTIONAL_SUITABILITY        |
| User Story                  |  As a QoS Engineer/Software Designer, I want to annotate blueprint components with modeled constraints.        |
| Requirement               | In the GMT, a user must be able to define a set of constraints (based on the CDL) for one or more components.      |
| Extended Description  | Assuming there are a set of predefined constraints, a user must be able to use them an relate them to the corresponding components. It would be nice to have a graphical approach for common (built in) constraints, but we must allow the user to open the text editor to allow them to be more flexible.      |
| Affected Tools             | GRAPHMODEL_TOOL  |
| Means of Verification  | Unit testing, manual testing in the IDE based on case studies from T4.2.          |
| Dependency               | N/A       |

**Comment by miwurster** [comment]
@gcasale please review and approve.

Reduced priority to `SHOULD` as the actual definition of the constraints is done in the IDE. GMT instead offers the possiblity that users can click a button (creating `ServiceTemplate.cdl` file next to the actual `.tosca` file behind the scene) to open the IDE in a new window. Using the "jump to code" feature we can navigate to the location in the project explorer of Che where the respective `ServiceTemplate.cdl` file is located.

**Comment by gcasale** [comment]
Approved

**Comment by v-yussupov** [comment]
Addressed by eclipse#465 and eclipse#523
