### ISSUE TITLE
[R-T4.3-6] Integration with other RADON tools

### ISSUE THREAD

**Issue by v-yussupov** [radon-h2020/radon-gmt#9]
| **ID**                        |  **R-T4.3-6**                              |
|-----------------------|----------------------------------|
| Section                       |  WP4: Modeling Environment     |
| Type                           |  COMPATIBILITY   |
| User Story                  |  As a Software Designer/Software Developer/Operations Engineer, I want my modeling tool to support integrations to other ones.        |
| Requirement               | A user should be able to trigger certain tools from the modeling tool.      |
| Extended Description  | For example to trigger the decomposition tool or the verification tool.      |
| Affected Tools             | GRAPHMODEL_TOOL  |
| Means of Verification  | Manual testing in the IDE.          |
| Dependency               | T4.1; T3.2; T3.3       |

**Comment by naesheim** [comment]
Does this include the ability to model CTT tests?
@miwurster

**Comment by v-yussupov** [comment]
Hi @naesheim, #11 addresses specification of CTT test cases

**Comment by v-yussupov** [comment]
Integration specific to GMT (export/import of CSARs) is solved in the context of eclipse#465 and eclipse#523.
The RADON tools integration is achieved by means of [RADON IDE](https://github.com/radon-h2020/radon-ide)
